# Generated by Django 4.1.3 on 2022-12-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarnSpend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
