# Generated by Django 4.1.3 on 2022-12-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_money_delete_earnspend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='type',
            field=models.CharField(max_length=5),
        ),
    ]
