version: '3'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: finez_server
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - finez_network
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000

networks:
  finez_network:
    driver: bridge
